### ISSUE TITLE
版本问题与回放

### ISSUE THREAD

**Issue by xizai123** [AltmanD/guandan_mcc#10]
您好，python3.8只能对应2.2及以上的tensorflw，我该装哪个版本呢，我想得到对局回放，运行showdown程序就可以了吗，run
actor.py与run showdown里的clients有什么区别呢

**Comment by AltmanD** [comment]
这个库的代码只能支持 tf1.14 ，需要其他版本或 pytorch 的话需要自己修改一下。
对局回放只能通过 log 查看，showdown 是为了玩家手动参与对局设计的，不过可以尝试在 showdown 代码里换成四个 agent ，并添加合适的延迟来实现回放。
actor.py 是训练过程中采集数据的 agent ，clients 是训好模型后的推理端。

**Comment by xizai123** [comment]
您好，我在showdown运行actor.py时遇到了下面的问题
Traceback (most recent call last):
  File "/home/dcx/anaconda3/envs/guandan/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dcx/anaconda3/envs/guandan/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "actor.py", line 71, in exit_wrapper
    run_one_player(index, *x, **kw)
  File "actor.py", line 49, in run_one_player
    player = Player(args)
  File "actor.py", line 38, in __init__
    with open('/home/luyd/guandan_mcc/showdown/clients/dan.ckpt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/luyd/guandan_mcc/showdown/clients/dan.ckpt'

请问模型文件能发一下吗，仅仅用于自己跑demo,感激

**Comment by AltmanD** [comment]
https://github.com/submit-paper/Danzero_plus/blob/main/actor_torch/q_network.ckpt
