### ISSUE TITLE
模型文件

### ISSUE THREAD

**Issue by xizai123** [AltmanD/guandan_mcc#11]
您好，我在showdown运行actor.py时遇到了下面的问题
Traceback (most recent call last):
File "/home/dcx/anaconda3/envs/guandan/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/dcx/anaconda3/envs/guandan/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "actor.py", line 71, in exit_wrapper
run_one_player(index, *x, **kw)
File "actor.py", line 49, in run_one_player
player = Player(args)
File "actor.py", line 38, in init
with open('/home/luyd/guandan_mcc/showdown/clients/dan.ckpt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/luyd/guandan_mcc/showdown/clients/dan.ckpt'

请问模型文件能发一下吗，仅仅用于自己跑demo,感激

**Comment by AltmanD** [comment]
到我师弟的库里下载吧 https://github.com/submit-paper/Danzero_plus/blob/main/actor_torch/q_network.ckpt ，另外他还做了增强版也挺好的，可以玩玩

**Comment by XliOK** [comment]
你们有遇到剩下两家，有一家手里是["6♦️","8♦️"]，另一家手牌是["10♠️","J♠️"]，然后前面那家打了8♦️，后面这家直接pass吗

**Comment by AltmanD** [comment]
一般只关注总胜率，Q 网络这版还是比较菜的，偶尔有些情况会抽风，但是你给的这个判例大小关系这么明显应该还是能处理的，不至于直接pass
